const salutation = "//*[@id="salutation"]"
const firstName = "//*[@id="firstName"]"
const lastName = "//*[@id="lastName"]"
const Email = "/html/body/div[13]/div/div[1]/form/div/div[4]"
const password = "//*[@id="container_password"]"
const password2 = "//*[@id="password2"]"
const checkBox1 = "//*[@id="register-form"]/div/div[11]/div/div/span[1]"
const checkBox2 = "//*[@id="register-form"]/div/div[12]/div/div/span[1]"
const submit = "//*[@id="register-submit"]"

const firstNameError = "//*[@id="firstName-error"]/font/font"
const lastNameError = "//*[@id="lastName-error"]/font/font"
const EmailEror = "//*[@id="email-error"]/font/font"
const passwordError = "//*[@id="password-error"]/font/font"
const password2Error = "//*[@id="password2-error"]/font/font"
const checkBox2Error = "//*[@id="accountNew__agbBoxErrorId"]/font/font"
