const salutation = "//select[@id='salutation']"
const firstName = "//input[@id='firstName']"
const lastNAme = "//input[@id='lastName']"
const emailNewAccount = ".accountNew > .formInput.formInput--text > .formInput__inputContainer > #email"
const password = "//input[@id='password']"
const password2 = "//input[@id='password2']"
const checkbox1 = "//span[@class='checkbox__checkbox checkbox__checkbox--alignTop checkbox__checkbox--//"
const checkBox2 = "//span[@class='checkbox__checkbox checkbox__checkbox--alignTop']"
const buttonSubmit = "//button[@id='register-submit']"
const email = "//input[@id='email'and@class='input input----text']"

